apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace will set in ArgoCD. This will allow just copying this promotion 
# namespace: dev-quarkus-demo
resources:
- namespace.yaml
- route.yaml
- ../../base
- ./pipeline

images:
- digest: sha256:04b3f6e361f3ebd3b08b6f2bc5c7d13e8ab8f3641db8ffd1208b60cbb6719f26
  name: quarkus-demo
  newName: quay.io/ssm/quarkus-demo
commonAnnotations:
  git-commit.sha: e9c469a133027d6f70919c6bd4984d196c26b4bb
  sha: sha25611
