apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace will set in ArgoCD. This will allow just copying this promotion 
# namespace: dev-quarkus-demo
resources:
- namespace.yaml
- route.yaml
- ../../base

images:
- digest: sha256:ae2ab4deae4ed73635b105d64b2bf706cf9fb30b1ce260dd0da8317ac94e744c
  name: quarkus-demo
  newName: quay.io/ssm/quarkus-demo
commonAnnotations:
  git-commit.sha: e8f836fa78223091311584c0048c646970875e9f
  sha: sha25611
