apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace will set in ArgoCD. This will allow just copying this promotion 
# namespace: dev-quarkus-demo
resources:
- ../../base

images:
- digest: sha256:4cd9329c758b71736cad3a63879a3c76e354eff663b5405a5c9826e4494e1055
  name: quarkus-demo
  newName: image-registry.openshift-image-registry.svc:5000/dev-quarkus-demo/quarkus-demo
commonAnnotations:
  git-commit.sha: e9c469a133027d6f70919c6bd4984d196c26b4bb
  sha: sha25611
