apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace will set in ArgoCD. This will allow just copying this promotion 
# namespace: dev-quarkus-demo
resources:
- ../../base

images:
- digest: sha256:c7118db0121af6eb21777e52e8e0bd52360f39ee5196224500d8ffa9c9764bd8
  name: quarkus-demo
  newName: quay.io/ssm/quarkus-demo
commonAnnotations:
  git-commit.sha: e9c469a133027d6f70919c6bd4984d196c26b4bb
  sha: sha25611
