apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace will set in ArgoCD. This will allow just copying this promotion 
# namespace: dev-quarkus-demo
resources:
- ../../base

images:
- name: quarkus-demo
  newName: image-registry.openshift-image-registry.svc:5000/dev-quarkus-demo/quarkus-demo
  newTag: e9c469a
commonAnnotations:
  git-commit.sha: e9c469a
  sha: sha25611
