apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace will set in ArgoCD. This will allow just copying this promotion 
# namespace: dev-quarkus-demo
resources:
- ../../base

images:
- digest: sha256:af82d519397680fd59704a7d8bc43effb82472a05ee30ffad127751532fb035b
  name: quarkus-demo
  newName: quay.io/ssm/quarkus-demo
commonAnnotations:
  git-commit.sha: e9c469a133027d6f70919c6bd4984d196c26b4bb
  sha: sha25611
