apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

# Namespace will set in ArgoCD. This will allow just copying this promotion
# namespace: quarkus-demo

commonLabels:
  app: quarkus-demo
